spring.application.name=gateway

server.port=8890
eureka.client.service-url.defaultZone =  http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true



spring.cloud.gateway.routes[0].id=logging-service
spring.cloud.gateway.routes[0].uri=lb://logging-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/logging/**


spring.cloud.gateway.routes[1].id=facade-service
spring.cloud.gateway.routes[1].uri=lb://facade-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/facade/**


spring.cloud.gateway.routes[2].id=messaging-service
spring.cloud.gateway.routes[2].uri=lb://messaging-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/messaging/**