spring.application.name=messaging-service
server.port=0
eureka.client.service-url.defaultZone =  http://localhost:8761/eureka/


spring.kafka.consumer.group-id=group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.admin.auto-create=true

