spring.application.name=facade-service
server.port=0

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


eureka.instance.instance-id=${spring.application.name}:${random.int[1000,9999]}

eureka.instance.hostname=localhost

eureka.instance.prefer-ip-address=true

eureka.client.instance-info-replication-interval-seconds=5

eureka.instance.lease-renewal-interval-in-seconds=1
eureka.instance.lease-expiration-duration-in-seconds=2

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.linger-ms=5
spring.kafka.producer.batch-size=16384
spring.kafka.producer.compression-type=gzip
spring.kafka.producer.enable-idempotence=true

eureka.client.service-url.defaultZone =  http://localhost:8761/eureka/

